<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah ke keranjang</name>
   <tag></tag>
   <elementGuidId>db8e8ce0-8ffb-43bf-b541-dc13ff0b90c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='product-addtocart-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-addtocart-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29650e6c-c269-4e9d-8afd-5aacf9886d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>462a1aa1-50b6-433a-97fe-7f8f7228bb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tambah ke keranjang</value>
      <webElementGuid>5655b65e-a45b-433b-8298-3e381df92d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action primary tocart</value>
      <webElementGuid>9f8ff63c-c3ed-4f02-a0e1-4a22630df890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-addtocart-button</value>
      <webElementGuid>6ba5ae34-d23d-4f5a-a825-21f5a09b71da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah ke keranjang</value>
      <webElementGuid>8482e5d0-bf20-4ccd-b2ef-ec0ef6e58c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-addtocart-button&quot;)</value>
      <webElementGuid>5106232b-c935-4b1b-8d6c-9eb759f78eaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='product-addtocart-button']</value>
      <webElementGuid>a4dd5d34-d258-4dce-9cde-f52f8bdba201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div/div[3]/div/div[2]/button</value>
      <webElementGuid>e66171e5-3590-46ca-8598-402cb46de4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='barang'])[1]/following::button[1]</value>
      <webElementGuid>7f69ef59-8927-46ab-9218-c1f8496521d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambahkan ke Daftar Keinginan'])[1]/following::button[1]</value>
      <webElementGuid>bca74ee6-82d5-4abe-a7b5-ed0c6c2ed7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pergi Ke Keranjang'])[1]/preceding::button[1]</value>
      <webElementGuid>6527d043-4638-4d17-b1cc-363b137e6326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button</value>
      <webElementGuid>6de6dbc4-a721-4878-b9ec-8041377c2db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Tambah ke keranjang' and @id = 'product-addtocart-button' and (text() = 'Tambah ke keranjang' or . = 'Tambah ke keranjang')]</value>
      <webElementGuid>654a199a-be5f-410f-8480-932710a089db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
