<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cole Short Pants Knit Pique With Pintuck</name>
   <tag></tag>
   <elementGuidId>626b6947-b8a9-4010-821e-b3402ff77ea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amasty-shopby-product-list']/div[3]/ol/li[2]/div/div/strong/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72a95b79-5d4b-47d9-a9f0-2d97361c96a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-item-link</value>
      <webElementGuid>642fd3ac-127e-4624-9c02-2156c5b4bee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.matahari.com/117930358.html</value>
      <webElementGuid>b38b8c06-ff47-462a-b570-fc12197e03f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cole Short Pants Knit Pique With Pintuck</value>
      <webElementGuid>57723cfd-752d-4d07-a63f-9d1e96a54334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amasty-shopby-product-list&quot;)/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/div[@class=&quot;product details product-item-details&quot;]/strong[@class=&quot;product name product-item-name&quot;]/a[@class=&quot;product-item-link&quot;]</value>
      <webElementGuid>df074391-fecc-4e74-96b1-a44ad01a4b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amasty-shopby-product-list']/div[3]/ol/li[2]/div/div/strong/a</value>
      <webElementGuid>a30c28d3-cdef-4bf7-a3d4-5efe993a0c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cole Short Pants Knit Pique With Pintuck')]</value>
      <webElementGuid>f8e45764-48f1-4172-a401-1f5169f1fefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cole'])[3]/following::a[1]</value>
      <webElementGuid>be1544ab-e3dd-47b1-b01c-fb63437f13fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambahkan ke Daftar Keinginan'])[2]/following::a[1]</value>
      <webElementGuid>53f81b8e-3807-4a5f-b534-7bf9e4497601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 91,960'])[2]/preceding::a[1]</value>
      <webElementGuid>6ca4d946-66e0-4dc3-8a98-bd6a8a0a17eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 229,900'])[2]/preceding::a[1]</value>
      <webElementGuid>4ec2031f-c017-477f-92e1-7249cef7b78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cole Short Pants Knit Pique With Pintuck']/parent::*</value>
      <webElementGuid>1f6c4edb-ff04-4791-92cb-698059456f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.matahari.com/117930358.html')])[2]</value>
      <webElementGuid>7a8feb9c-9614-495c-a69d-4d8136ef06ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/strong/a</value>
      <webElementGuid>c38659ae-2755-4344-b03d-217007b6ce0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.matahari.com/117930358.html' and (text() = 'Cole Short Pants Knit Pique With Pintuck' or . = 'Cole Short Pants Knit Pique With Pintuck')]</value>
      <webElementGuid>d279827f-6f24-48bf-885d-1b2ee718c545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
